build_from:
  aarch64: python:3.11-slim-bookworm
  amd64: python:3.11-slim-bookworm
  armhf: python:3.11-slim-bookworm
  armv7: python:3.11-slim-bookworm
  i386: python:3.11-slim-bookworm
args:
  version: "1.0.9"
