build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian-python:3.11-bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian-python:3.11-bookworm
  armhf: ghcr.io/home-assistant/armhf-base-debian-python:3.11-bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian-python:3.11-bookworm
  i386: ghcr.io/home-assistant/i386-base-debian-python:3.11-bookworm
